language: go
go:
  - 1.9
  - 1.8
  - 1.7
  - tip
install:
  - make installdeps
cache:
  directories:
    - vendor
    - glide-$(go version | awk '{ print $NF }' | tr '/' '-')
before_script:
  - make generate
  - git diff | test -z
script:
  - make test