language: go
go:
  - 1.7.4
  - tip
install:
  - make installdeps
cache:
  directories:
    - vendor
    - glide-$(go version | awk '{ print $NF }' | tr '/' '-')
before_script:
  - make generate
  - [ -z "$(git diff)" ]
script:
  - make test